# Generated by Django 5.1.7 on 2025-03-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.TextField(max_length=20)),
                ('days', models.CharField(max_length=10)),
                ('people', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='destinations/')),
            ],
        ),
    ]
