# Generated by Django 5.1.7 on 2025-03-15 22:16

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name=django.contrib.auth.models.User)),
                ('user_fullname', models.CharField(blank=True, max_length=200)),
                ('user_phone', models.CharField(blank=True, max_length=7)),
                ('user_email', models.EmailField(blank=True, max_length=200)),
                ('selected_trip', models.CharField(max_length=100)),
                ('number_of_travelers', models.CharField(max_length=3)),
                ('travel_date', models.CharField(max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
