# Generated by Django 5.1.1 on 2025-03-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_travelers',
            field=models.IntegerField(),
        ),
    ]
