# Generated by Django 5.1.1 on 2025-03-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0003_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
