# Generated by Django 5.1.1 on 2025-03-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0004_remove_booking_travel_date_alter_booking_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
