# Generated by Django 5.1.1 on 2025-03-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0005_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='To_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='from_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
