# Generated by Django 5.1.1 on 2025-03-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0006_booking_to_date_booking_from_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='To_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='from_date',
        ),
        migrations.AddField(
            model_name='destination',
            name='To_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='from_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
