# Generated by Django 5.1.7 on 2025-03-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0007_remove_booking_to_date_remove_booking_from_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
        ),
    ]
