# Generated by Django 5.1.7 on 2025-04-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0009_alter_subscribe_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=20)),
                ('discount_percentage', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
