# Generated by Django 5.1.7 on 2025-04-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0010_promocode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='days',
            new_name='days_and_nights',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='people',
            new_name='max_people',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='price',
            new_name='price_per_person',
        ),
        migrations.AddField(
            model_name='destination',
            name='second_To_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='destination',
            name='second_from_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
