# Generated by Django 5.1.7 on 2025-04-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0011_rename_days_destination_days_and_nights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayementProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.ImageField(max_length=12, upload_to='')),
                ('trip_title', models.CharField(max_length=100)),
                ('transfer_date', models.DateField()),
                ('screenshot', models.ImageField(upload_to='payment_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
