# Generated by Django 5.1.7 on 2025-04-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0012_payementproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payementproof',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
