# Generated by Django 5.1.7 on 2025-04-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0013_alter_payementproof_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='days_and_nights',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='max_people',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payementproof',
            name='screenshot',
            field=models.ImageField(upload_to='paymentProofs/'),
        ),
    ]
