# Generated by Django 5.1.7 on 2025-04-28 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0014_alter_destination_days_and_nights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=50)),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Destinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs', to='travelApp.destination')),
            ],
        ),
    ]
