# Generated by Django 5.1.7 on 2025-04-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0015_tarif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarif',
            old_name='Destinations',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='tarif',
            old_name='price_per_person',
            new_name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite')], max_length=20),
        ),
    ]
