# Generated by Django 5.1.7 on 2025-04-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0016_rename_destinations_tarif_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payementproof',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
