# Generated by Django 5.1.7 on 2025-04-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0017_alter_payementproof_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='has_multiple_tarifs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='price_per_person',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
