# Generated by Django 5.1.7 on 2025-04-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0018_destination_has_multiple_tarifs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='tarif',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
