# Generated by Django 5.1.7 on 2025-04-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0019_destination_tarif_alter_destination_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='room_type',
            field=models.CharField(choices=[('Double', 'Double'), ('Single', 'Single'), ('Enfant', 'Enfant'), ('CHD sans-lit', 'CHD sans-lit'), ('CHD avec-lit', 'CHD avec-lit')], max_length=20),
        ),
    ]
