# Generated by Django 5.1.7 on 2025-04-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0021_destination_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='tarif',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
