# Generated by Django 5.1.7 on 2025-04-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0022_alter_destination_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='tarif',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
