# Generated by Django 5.1.7 on 2025-04-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0024_alter_destination_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
