# Generated by Django 5.1.7 on 2025-05-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0026_alter_payementproof_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payementproof',
            name='phone',
            field=models.IntegerField(max_length=13),
        ),
    ]
