# Generated by Django 5.1.7 on 2025-05-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0028_alter_payementproof_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payementproof',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
