# Generated by Django 5.1.7 on 2025-05-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0029_alter_payementproof_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
