# Generated by Django 5.1.7 on 2025-05-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0030_alter_booking_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
