# Generated by Django 5.1.7 on 2025-05-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0031_alter_destination_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='days_and_nights',
            field=models.CharField(max_length=25),
        ),
    ]
