# Generated by Django 5.1.7 on 2025-05-26 22:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0032_alter_destination_days_and_nights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='destinations'),
        ),
    ]
